config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :subjects do
    resources :attendances, only: [:index, :show, :create]
  end

  root controller: 'welcome', action: :index
  post '/SubjectCreate', to: 'subject#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :subject
end

app/models/subject.rb
class Subject < ApplicationRecord
  before_validation :time_has_a_date
  reverse_geocoded_by :latitude, :longitude
  after_validation :reverse_geocode  # auto-fetch address
  has_many :attendances, dependent: :destroy
  # validates :latitude, :longitude, :radius, presence: true

  private
	  def time_has_a_date
	    self.start_time = self.start_time.change(year: self.date.year, day: self.date.day, month: self.date.month)
	  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session

  def after_sign_in_path_for(resource)
    sign_in_url = new_user_session_url
    if request.referer == sign_in_url
      super
    else
      stored_location_for(resource) || request.referer || root_path
    end
  end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :set_attendance, only: [:show]
  before_action :authenticate_user!, except: [:create]
  def create
    @attendance = current_subject.attendances.build(attendance_params)
    @attendance.subject_id = current_subject.id
    point1 = [@attendance.latitude, @attendance.longitude]
    point2 = [current_subject.latitude, current_subject.longitude]
    radius = current_subject.radius
    distance = Geocoder::Calculations.distance_between(point1, point2) * 1000
    in_circle = distance < radius
    start_seconds = current_subject.start_time.seconds_since_midnight
    end_seconds = current_subject.end_time.seconds_since_midnight
    range = start_seconds..end_seconds
    t = attendance_params["created_at"]
    new_time = Time.parse(t)
    client_seconds = new_time.seconds_since_midnight
    in_progress = range === client_seconds
    if in_circle
      # if in_progress
        if @attendance.save!
          render json: @attendance, status: :created
        else
          head(:unprocessable_entity)
        end
      # else
      #   render json: {faile: 'Время проверки пока не началось или уже прошло'}, status: :forbidden
      # end
    else
      render json: {faile: 'Не надо так. Вы не в радиусе класса'}, status: :forbidden
    end
  end

  def index
    @subject = Subject.find(params[:subject_id])
    @attendances = current_subject.attendances.order('created_at ASC')
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @attendances, status: :ok}
    end
  end

  def show

  end


  private

    def current_subject
      @current_subject = Subject.find(params[:subject_id])
    end

    def set_attendance
      @subject = current_subject.attendances.find(params[:id])
    end

    def attendance_params
      params.require(:attendance).permit(:first_name, :last_name,:longitude, :latitude, :subject_id, :created_at)
    end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]
  # GET /subjects
  # GET /subjects.json
  def index
    @subjects = Subject.all
    @hash = Gmaps4rails.build_markers(@subjects) do |subject, marker|
      marker.lat subject.latitude
      marker.lng subject.longitude
      marker.infowindow subject.name
    end
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @subjects, status: :ok}
    end
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
    @hash = Gmaps4rails.build_markers(@subject) do |subject, marker|
      marker.lat subject.latitude
      marker.lng subject.longitude
      marker.infowindow subject.name
    end
  end

  # GET /subjects/new
  def new
    @subject = Subject.new
  end

  # GET /subjects/1/edit
  def edit
  end

  # POST /subjects
  # POST /subjects.json
  def create
    params[:subject].parse_time_select! :start_time
    params[:subject].parse_time_select! :end_time
    # params[:subject].parse_time_select! :date
    @subject = Subject.new(subject_params)

    respond_to do |format|
      if @subject.save!
        format.html { redirect_to @subject, notice: 'Subject was successfully created.' }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1
  # PATCH/PUT /subjects/1.json
  def update
    params[:subject].parse_time_select! :start_time
    params[:subject].parse_time_select! :end_time
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to @subject, notice: 'Subject was successfully updated.' }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to subjects_url, notice: 'Subject was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subject_params
      params.require(:subject).permit(:name, :longitude, :latitude, :radius,  :start_time, :end_time, :date)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/attendances/index.html.erb
<h1>Список посещаемости для  <%= @subject.name %></h1>
<% if @attendances.any? %>
<table class="table table-hovered table-bordered">
  <thead>
    <tr>
      <th>Имя</th>
      <th>Фамилия</th>
      <th>Время</th>
    </tr>
  </thead>

  <tbody>
      <% @attendances.each do |attendance| %>
        <tr>
          <td><%= attendance.first_name %></td>
          <td><%= attendance.last_name %></td>
          <td><%= attendance.created_at %></td>
        </tr>
      <% end %>
  </tbody>
</table>
<% else %>
  <p>Посещаемости нету</p>
<% end %>
<br>
<%= link_to "Назад", :back %>

app/views/attendances/show.html.erb
<h1>Attendances#show</h1>
<p>Find me in app/views/attendances/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yatut</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <style>
    nav a { color: white; }
    nav a:hover { color: #4CCFF3; }
    nav{
      margin-bottom: 1rem;
    }
  </style>
  <body>
  <nav style="background-color:#34495e;" class="navbar">
  <%= link_to "Yatut", root_path, class:"navbar-brand" %>

    <ul class="nav">
      <% if user_signed_in? %>
      <li class="nav-item"><%= link_to 'События', subjects_path, class:"nav-link" %></li>
      <li class="nav-item"><%= link_to "Мой аккаунт", edit_user_registration_path,  class:"nav-link" %></li>      
      <li class="nav-item"><%= link_to 'Выйти', destroy_user_session_path, class:"nav-link", method: :delete %></li>
      <% else %>
      <li class="nav-item"><%= link_to "Зарегистрироваться", new_user_registration_path, class:"nav-link" %></li>
      <li class="nav-item"><%= link_to "Войти", new_user_session_path, class:"nav-link" %></li>
      <% end %>
    </ul>
  </nav>
    <div class="container">
        <% if alert %>
          <p class="alert alert-warning" role="alert"><%= alert%></p>
        <% end%>
        <% if notice %>
          <p class="alert alert-success" role="alert"><%= notice%></p>
        <% end%>
      <%= yield %>
    </div>
  </body>
</html>

app/views/subjects/_form.html.erb
<%= form_with(model: subject, local: true) do |form| %>
<% if subject.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

    <ul>
    <% subject.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<div class="row">
<div class="col-md-4">
<div class="field">
  <%= form.label 'Название' %>
  <%= form.text_field :name, class: "form-control", required: true%>
</div>

<div class="field">
  <%= form.label 'Дата' %>
  <%= form.date_select :date, class: "form-control", required: true%>
</div>

<div class="field">
  <%= form.label 'Начинается в' %>
  <%= form.time_select :start_time,
    :combined => true,
    :default => Time.now.change(:hour => 11, :min => 30),
    :minute_interval => 20,
    :time_separator => "",
    :start_hour => 6,
    :start_minute => 30,
    :end_hour => 20,
    :end_minute => 30,
    class: "form-control",
    required: true %>
</div>

<div class="field">
  <%= form.label 'Заканчивается в' %>
  <%= form.time_select :end_time,
    :combined => true,
    :default => Time.now.change(:hour => 11, :min => 30),
    :minute_interval => 10,
    :time_separator => "",
    :start_hour => 6,
    :start_minute => 30,
    :end_hour => 20,
    :end_minute => 30,
    class: "form-control",
    required: true %>
</div>


<div class="field">
  <%= form.hidden_field :latitude, id: "latitude", required: true %>
</div>


<div class="field">
  <%= form.hidden_field :longitude, id: "longitude", required: true %>
</div>

<div class="field">
  <%= form.label 'Радиус' %>
  <%= form.number_field :radius, class: "form-control", id:"radius", required: true %>
</div>

<div class="actions">
  <%= form.submit 'Создать событие', style:"margin: 20px 0 20px 0;", class:"btn btn-primary form-control", id:"submit_button"  %>
</div>

</div>
<div class="col-md-6">
  <div style='margin-top: 20px;'>
    <div id="map" style='width: 720px; height: 348px;'></div>
  </div>
</div>

</div>
<%= link_to 'Показать', @subject, class:"btn btn-info" %> 

<%= link_to 'Назад', subjects_path, class:"btn btn-primary" %>

<% end %>
</div>

<script>

function initMap() {
  var marker;
  var circle;
  var radius;
  var map = new google.maps.Map(document.getElementById('map'), {
    center: {lat: 43.20757, lng:76.670019},
    zoom: 15
  });
  var infoWindow = new google.maps.InfoWindow({map: map});

  if (navigator.geolocation) {
    navigator.geolocation.getCurrentPosition(function(position) {
      var pos = {
        lat: position.coords.latitude,
        lng: position.coords.longitude
      };

      infoWindow.setPosition(pos);
      infoWindow.setContent('Найдено ваше местоположение. Выберите центр аудитории');
      map.setCenter(pos);
      map.setZoom(15);
    }, function() {
      handleLocationError(true, infoWindow, map.getCenter());
    });
  } else {
    handleLocationError(false, infoWindow, map.getCenter());
  }


  function handleLocationError(browserHasGeolocation, infoWindow, pos) {
  infoWindow.setPosition(pos);
  infoWindow.setContent(browserHasGeolocation ?
                        'Error: The Geolocation service failed.' :
                        'Error: Your browser doesn\'t support geolocation.');
  }
  map.addListener('click', function(e){
    placeMarkerAndPanTo(e.latLng, map);
  });
  function placeMarkerAndPanTo(latLng, map){
    if ( marker ) {
      marker.setPosition(latLng);
    }
    else{
      marker = new google.maps.Marker({
        position: latLng,
        map: map
      });
    }
    bindWithFields(latLng);
    map.panTo(latLng);
    if (circle){
      circle.setRadius(radius)
    }
    else{
      circle = new google.maps.Circle({
        map: map,
        radius: radius,
        strokeColor: '#FF0000'
      });
      circle.bindTo('center', marker, 'position');
    }
  }
  function bindWithFields(latLng){
    document.getElementById('longitude').value = latLng.lng()
    document.getElementById('latitude').value = latLng.lat()
  }

  document.getElementById("radius").addEventListener('change', doThing);
  function doThing(){
    radius = Number(this.value);
    console.log(radius);
  }
}
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBj_0GBAd1mmKjDg9M2wHE4YoFF9J2-1hA&callback=initMap" async defer>
</script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>

app/views/subjects/edit.html.erb
<h1>Редактировать событие</h1>

<%= render 'form', subject: @subject %>

app/views/subjects/index.html.erb
<div class="row">
  <div class="col-md-10">
  <h1>События</h1>
  <table style="width: auto;" class="table table-hover table-bordered">
    <thead>
      <tr>
        <th>Название</th>
        <th>Адрес</th>        
      </tr>
    </thead>
    <tbody>
      <% @subjects.each do |subject| %>
        <tr>
          <td><%= link_to subject.name, subject %></td>
          <td><%= subject.address %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  </div>
  <div class="col-md-2 ">
    <%= link_to 'Новое событие', new_subject_path, class:"btn btn-primary" %>
  </div>
</div>

app/views/subjects/new.html.erb
<h1>Новое событие</h1>

<%= render 'form', subject: @subject %>

app/views/subjects/show.html.erb
<h1>
    <%= @subject.name %>
</h1>
<div class="row">
<div class="col-md-4">
<p>
  <strong>Широта:</strong>
  <%= @subject.latitude %>
</p>

<p>
  <strong>Долгота:</strong>
  <%= @subject.longitude %>
</p>

<p>
  <strong>Радиус:</strong>
  <%= @subject.radius %>
</p>

<p>
  <strong>Адрес:</strong>
  <%= @subject.address %>
</p>

<p>
  <strong>Дата:</strong>
  <%= @subject.date %>
</p>

<p>
  <strong>Начинается в:</strong>
  <%= @subject.start_time.strftime("%H:%M")%>
</p>

<p>
  <strong>Заканичается в:</strong>
  <%= @subject.end_time.strftime("%H:%M") %>
</p>


<%= link_to 'Редактировать', edit_subject_path(@subject), class:"btn btn-primary" %> 
<%= link_to 'Удалить', @subject, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger"  %> 
<%= link_to 'Назад', subjects_path, class:"btn btn-primary" %>

</div>
<div class="col-md-3">
<div >
  <div id="map" style='margin-bottom: 20px;width: 700px; height: 348px;'></div>
</div>

<%= link_to image_tag("icons/calendar.png", border: 0), subject_attendances_path(@subject), class: 'btn btn-primary' %>

</div>
</div>


<script>
function initMap(){
    var roomCenter = {lat: <%= @subject.latitude %>, lng: <%= @subject.longitude %>};
    var map = new google.maps.Map(document.getElementById('map'), {
      zoom: 18,
      center: roomCenter
    });
    var marker = new google.maps.Marker({
      position: roomCenter,
      map: map
    });

    var roomCircle = new google.maps.Circle({
      strokeColor: '#FF0000',
      strokeOpacity: 0.8,
      strokeWeight: 2,
      fillColor: '#FF0000',
      fillOpacity: 0.35,
      map: map,
      center: {lat: <%= @subject.latitude %>, lng: <%= @subject.longitude %>},
      radius: <%= @subject.radius %>
    });
  }
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBj_0GBAd1mmKjDg9M2wHE4YoFF9J2-1hA&callback=initMap" async defer>
</script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>

app/views/welcome/index.html.erb
<div class="container">
  <div class="col-xs-6" align="center">
    <h1>Yatut - простой инструмент для проверки посещаемости</h1>
    <p class="lead" align="center">Если вы администратор, то создать событие - это проще простого. 
    При создании события, вы задаёте координаты центра нужного помещения и радиус. <br>
    С помощью Telegram бота @yatut_bot, ваши студенты или сотрудники 
    могут заверить, что присутствовали на событии.
    Если пользователь бота, во время проверки посещаемости, находится в радиусе события, то тогда он успешно прошел проверку.</p>
   <h2 class="centered">Как пользоваться ботом Yatut?</h2> 
  
  </div>

 
  <div class="row"  align="center">
  <div class="col-md-6">
    <%= image_tag "photo1.jpg", class:"img-responsive screenshot" %>  
  </div>

  <div class="col-md-6">
    <p>1. Если вы администратор, то создать событие - это проще простого. При создании события, вы задаёте координаты центра нужного помещения и радиус. </p>
  </div>
  </div>
</div>